=head1 NAME

Attean::API::AggregateExpression - Role representing an aggregate expression tree

=head1 VERSION

This document describes Attean::API::AggregateExpression version 0.001_01

=head1 SYNOPSIS

  use v5.14;
  use Attean;

=head1 DESCRIPTION

This is a Moo role representing aggregate expressions.

=head1 ROLES

This role consumes L<Attean::API::DirectedAcyclicGraph>.

=head1 REQUIRED METHODS

Classes consuming this role must provide the following methods:

=over 4

=item C<< operator() >>

The name of the aggregate operator.

=item C<< scalar_vars() >>

A HASH reference of scalar variables. The only scalar variable defined for
SPARQL 1.1 is C<'seperator'>, a string separator used with the GROUP_CONCAT
aggregate.

=back

=head1 BUGS

Please report any bugs or feature requests to through the GitHub web interface
at L<https://github.com/kasei/attean/issues>.

=head1 SEE ALSO

L<http://www.perlrdf.org/>

=head1 AUTHOR

Gregory Todd Williams  C<< <gwilliams@cpan.org> >>

=head1 COPYRIGHT

Copyright (c) 2014 Gregory Todd Williams.
This program is free software; you can redistribute it and/or modify it under
the same terms as Perl itself.

=cut
