name: issue-notify

on:
  issues:
    types: [opened,assigned,closed,reopened]
  issue_comment:
    types: [created]
  pull_request:
    types: [closed,assigned,converted_to_draft,ready_for_review,review_requested]
  pull_request_review:
    types: [submitted]

env:
  IRC_REPO_OWNER: 'kasei'

jobs:
  notify:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ always() }}
    steps:
      - uses: perlrdf/devops/github-actions/irc-notifications@main
        with:
          target-notifications: true
          repository_owner: ${{ env.IRC_REPO_OWNER }}
